services:
  mongo-auth-db:
    container_name: mongo_auth_database
    image: mongo:latest
    restart: always
    command: ["--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo-keyfile"]
    volumes:
      - ./mongo:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=123456